//document.write('<table width="100%" border="0" cellspacing="0" cellpadding="0">\n');
//document.write('<tr><td width="100%" style="background-color: #bbbbbb; color: #000000; font-size: 11px; padding: 3px 8px; border-bottom: 2px solid #888888; font-family: "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif; font-size: 11px; line-height: 1.3; font-weight: normal">\n');
//document.write('morn proudly presents: ');
//document.write('<a style="text-decoration: none; color: #EEEEEE; font-weight: bold" href="http://www.mans.de">mans.de</a> :: ');
//document.write('<a style="text-decoration: none; color: #EEEEEE; font-weight: bold" href="http://www.planetcrap.com">planetcrap</a> :: ');
//document.write('<a style="text-decoration: none; color: #EEEEEE; font-weight: bold" href="http://www.crapradio.org">crapradio</a> :: ');
//document.write('<a style="text-decoration: none; color: #EEEEEE; font-weight: bold" href="http://www.mornography.de">mornography</a> :: ');
//document.write('<a style="text-decoration: none; color: #EEEEEE; font-weight: bold" href="http://g-blog.net/user/Morn">morn.g-blog.net</a>\n');
//document.write('</td></tr></table>\n');
document.write('<iframe name="mornbar" src="http://www.planetcrap.com/crapnet/crapbar-src.php" scrolling="no" style="width: 100%; height: 25px; border: none; margin: 0px;"></iframe>\n');
